data:
  data_path: None # Dataset path for unprocessed data
  target_data_path: './split_data' # Dataset path for processed data
  length_seconds: 10 # Segment length in seconds
  target_sr: 48000 # Target sampling rate
  train_split: 0.95 # Training dataset ratio

feature:
  n_win: 1200
  n_fft: 1200
  n_hop: 600
  n_comp: 256

train:
  device: 'cuda:0'
  device_ids: [0,1,2,3]
  length_in_seconds: 4 # in seconds
  epochs: 200
  batch_size: 4
  num_workers: 8
  k1: 0.2
  k2: 4e-4
  warmup: 4000

log:
  name: 'dptfsnet_scm'
  ckpt_dir: './ckpt/dptfsnet_scm'
